name: Build on DinD
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 
      - self-hosted
      - dind
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker Build
        shell: bash
        run: |
          docker build . -t ghcr.io/${GITHUB_REPOSITORY,,}-dind:$(date +%Y%m%d.$GITHUB_RUN_NUMBER)
          docker images
      - name: Docker Push
        shell: bash
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u dkoch84 --password-stdin
          docker push ghcr.io/${GITHUB_REPOSITORY,,}-dind:$(date +%Y%m%d.$GITHUB_RUN_NUMBER)
