name: Puppeteer Base Image

on:
  push:
    branches:
      - main
    paths-ignore: 
      - README.md
      - .gitignore
      - .github/**
  workflow_dispatch:
    
jobs:
  container:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: puppeteer
    steps:    
    - uses: actions/checkout@v2
    - name: Docker Build
      shell: bash
      run: |
        DOCKER_BUILDKIT=1 docker build . -t ghcr.io/${GITHUB_REPOSITORY,,}/puppeteer:$(date +%Y%m%d.$GITHUB_RUN_NUMBER)
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Publish
      shell: bash
      run: |
        docker push ghcr.io/${GITHUB_REPOSITORY,,}/puppeteer:$(date +%Y%m%d.$GITHUB_RUN_NUMBER)